using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

var options = GeneratorOptions.Parse(args);
var repositoryRoot = Path.GetFullPath(options.RepositoryRoot);
var promptsRoot = Path.Combine(repositoryRoot, "prompts");
var manifestPath = Path.Combine(promptsRoot, "manifest.json");

if (!File.Exists(manifestPath))
    throw new InvalidOperationException($"Prompt manifest was not found at {manifestPath}.");

var manifest = JsonSerializer.Deserialize<PromptManifest>(
    File.ReadAllText(manifestPath),
    new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
    ?? throw new InvalidOperationException("The prompt manifest is empty.");

var templates = LoadTemplates(manifest, promptsRoot);
var failures = new List<string>();

if (options.Target is GenerationTarget.CSharp or GenerationTarget.All)
{
    var output = Path.Combine(repositoryRoot, "Mellow.Narrator.Core", "Generated", "PromptTemplates.g.cs");
    WriteOrCheck(output, GenerateCSharp(templates), options.CheckOnly, failures);
}

if (options.Target is GenerationTarget.TypeScript or GenerationTarget.All)
{
    var output = Path.Combine(repositoryRoot, "Mellow.Narrator.Web", "src", "app", "core", "prompt-templates.generated.ts");
    WriteOrCheck(output, GenerateTypeScript(templates), options.CheckOnly, failures);
}

if (failures.Count > 0)
{
    foreach (var failure in failures) Console.Error.WriteLine(failure);
    Environment.ExitCode = 1;
}

static IReadOnlyList<PromptTemplate> LoadTemplates(PromptManifest manifest, string promptsRoot)
{
    if (manifest.Templates.Count == 0)
        throw new InvalidOperationException("The prompt manifest contains no templates.");

    var keys = new HashSet<string>(StringComparer.Ordinal);
    var templates = new List<PromptTemplate>(manifest.Templates.Count);
    var placeholderPattern = new Regex(@"\{([A-Za-z][A-Za-z0-9]*)\}", RegexOptions.CultureInvariant);
    var normalizedRoot = Path.GetFullPath(promptsRoot) + Path.DirectorySeparatorChar;

    foreach (var definition in manifest.Templates)
    {
        if (!Regex.IsMatch(definition.Key, @"^[a-z][A-Za-z0-9]*$", RegexOptions.CultureInvariant))
            throw new InvalidOperationException($"Prompt key '{definition.Key}' must be lower camel case.");
        if (!keys.Add(definition.Key))
            throw new InvalidOperationException($"Prompt key '{definition.Key}' is duplicated.");

        var path = Path.GetFullPath(Path.Combine(promptsRoot, definition.File));
        if (!path.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException($"Prompt file '{definition.File}' is outside the prompts directory.");
        if (!File.Exists(path))
            throw new InvalidOperationException($"Prompt file '{definition.File}' does not exist.");

        var content = Normalize(File.ReadAllText(path));
        if (string.IsNullOrWhiteSpace(content))
            throw new InvalidOperationException($"Prompt file '{definition.File}' is empty.");

        var actualPlaceholders = placeholderPattern.Matches(content)
            .Select(match => match.Groups[1].Value)
            .ToHashSet(StringComparer.Ordinal);
        var declaredPlaceholders = definition.Placeholders.ToHashSet(StringComparer.Ordinal);
        if (!actualPlaceholders.SetEquals(declaredPlaceholders))
        {
            throw new InvalidOperationException(
                $"Prompt '{definition.Key}' placeholders do not match its manifest declaration. " +
                $"Declared: {string.Join(", ", declaredPlaceholders.Order())}. " +
                $"Found: {string.Join(", ", actualPlaceholders.Order())}.");
        }

        templates.Add(new PromptTemplate(definition.Key, content));
    }

    return templates;
}

static string GenerateCSharp(IReadOnlyList<PromptTemplate> templates)
{
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine("// Generated from /prompts. Do not edit this file directly.");
    builder.AppendLine();
    builder.AppendLine("namespace Mellow.Narrator.Core;");
    builder.AppendLine();
    builder.AppendLine("internal static class GeneratedPromptTemplates");
    builder.AppendLine("{");
    foreach (var template in templates)
    {
        if (template.Content.Contains("\"\"\"", StringComparison.Ordinal))
            throw new InvalidOperationException($"Prompt '{template.Key}' contains a C# raw-string delimiter.");

        builder.Append("    public const string ");
        builder.Append(ToPascalCase(template.Key));
        builder.AppendLine(" = \"\"\"");
        foreach (var line in template.Content.Split('\n'))
        {
            builder.Append("        ");
            builder.AppendLine(line);
        }
        builder.AppendLine("        \"\"\";");
        builder.AppendLine();
    }
    builder.AppendLine("}");
    return Normalize(builder.ToString()) + "\n";
}

static string GenerateTypeScript(IReadOnlyList<PromptTemplate> templates)
{
    var builder = new StringBuilder();
    builder.AppendLine("// AUTO-GENERATED from /prompts. DO NOT EDIT.");
    builder.AppendLine("export const promptTemplates = {");
    foreach (var template in templates)
    {
        builder.Append("  ");
        builder.Append(template.Key);
        builder.Append(": ");
        builder.Append(JsonSerializer.Serialize(template.Content));
        builder.AppendLine(",");
    }
    builder.AppendLine("} as const;");
    return Normalize(builder.ToString()) + "\n";
}

static void WriteOrCheck(string path, string content, bool checkOnly, ICollection<string> failures)
{
    var existing = File.Exists(path) ? Normalize(File.ReadAllText(path)) + "\n" : null;
    if (string.Equals(existing, content, StringComparison.Ordinal)) return;

    if (checkOnly)
    {
        failures.Add($"Generated prompt output is stale: {path}");
        return;
    }

    Directory.CreateDirectory(Path.GetDirectoryName(path)!);
    var temporary = path + "." + Guid.NewGuid().ToString("N") + ".tmp";
    File.WriteAllText(temporary, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    File.Move(temporary, path, overwrite: true);
    Console.WriteLine(path);
}

static string Normalize(string value) => value.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd('\r', '\n');

static string ToPascalCase(string value) => char.ToUpperInvariant(value[0]) + value[1..];

internal sealed record PromptManifest(IReadOnlyList<PromptDefinition> Templates);
internal sealed record PromptDefinition(string Key, string File, IReadOnlyList<string> Placeholders);
internal sealed record PromptTemplate(string Key, string Content);

internal enum GenerationTarget
{
    CSharp,
    TypeScript,
    All
}

internal sealed record GeneratorOptions(string RepositoryRoot, GenerationTarget Target, bool CheckOnly)
{
    public static GeneratorOptions Parse(string[] arguments)
    {
        var root = Directory.GetCurrentDirectory();
        var target = GenerationTarget.All;
        var checkOnly = false;

        for (var index = 0; index < arguments.Length; index++)
        {
            switch (arguments[index])
            {
                case "--root" when index + 1 < arguments.Length:
                    root = arguments[++index];
                    break;
                case "--target" when index + 1 < arguments.Length:
                    target = arguments[++index].ToLowerInvariant() switch
                    {
                        "csharp" => GenerationTarget.CSharp,
                        "typescript" => GenerationTarget.TypeScript,
                        "all" => GenerationTarget.All,
                        var value => throw new ArgumentException($"Unknown generation target '{value}'.")
                    };
                    break;
                case "--check":
                    checkOnly = true;
                    break;
                default:
                    throw new ArgumentException($"Unknown or incomplete argument '{arguments[index]}'.");
            }
        }

        return new GeneratorOptions(root, target, checkOnly);
    }
}
