import { AppSettings } from './models';

export const defaultSettings = (): AppSettings => ({
  key: 'app',
  baseUrl: 'https://api.openai.com/v1',
  modelId: '',
  apiKey: '',
  requestTimeoutSeconds: 120,
  maxOutputTokens: 4096,
  temperature: null,
  topP: null,
  reasoningEffort: '',
  recentTurnCount: 8,
  maxStoryBibleEntries: 200,
  maxStoryBibleEntryCharacters: 4000,
  maxStoryBibleCharacters: 60000,
  storyBibleWarningPercent: 80,
  maxPlannedEvents: 50,
  maxPlannedEventCharacters: 2000,
  maxPlannedEventsCharacters: 20000,
  plannedEventsWarningPercent: 80,
  minSuggestedActions: 2,
  maxSuggestedActions: 3,
  minParagraphs: 4,
  maxParagraphs: 6,
  maxStoryTitleCharacters: 200,
  maxStoryLabelCharacters: 200,
  maxStoryPromptCharacters: 20000,
  maxPlayerActionCharacters: 4000,
  maxNarrationCharacters: 20000,
  maxSuggestedActionCharacters: 500,
  maxStoryBibleCategoryCharacters: 100,
  maxStoryBibleNameCharacters: 200,
  maxStoryBibleUpdatesPerResponse: 100,
  maxPlannedEventDescriptionCharacters: 1000,
  maxPlannedEventConditionCharacters: 500,
  maxPlannedEventUpdatesPerResponse: 50,
  maxConditions: 20,
  maxConditionDescriptionCharacters: 1000,
  minSentencesPerParagraph: 2,
  maxSentencesPerParagraph: 5,
  maxAutomaticRetries: 2,
  retryInitialDelaySeconds: 1,
  retryMaxDelaySeconds: 10,
  retryMaxRetryAfterSeconds: 60,
  structuredOutputTier: 'untested',
  outputTokenParameter: 'maxCompletionTokens',
  instructionMessageRole: 'developer',
});

